---
title: "temperature"
format: 
  html:
    toc: true
    number-sections: true
editor: visual
---

```{r setup}
#| echo: true
#| code-fold: false
#| warning: false
#| message: false
library(tsibble)
library(tidyverse)
library(lubridate)
library(feasts)
library(fable)
library(here)
library(targets)
```

Load data

```{r}
daily <- tar_read(daily)
temp <- daily |> select(temp_air_meanC)
```

Fit models

```{r}
temp_train <- 
  temp |> 
  # filter(meta_station_id == "az01") |> 
  filter(meta_station_id %in% c("az01", "az02")) |> 
  filter(year(datetime) < 2022)

temp_test <- 
  temp |> 
  # filter(meta_station_id == "az01") |> 
  filter(meta_station_id %in% c("az01", "az02")) |> 
  filter(year(datetime) >= 2022)

fit_compare <- 
  temp_train |> 
  model(
    snaive = SNAIVE(temp_air_meanC ~ lag("365 days")), # equivalent to ARIMA(0,0,0)(0,1,0)[365]
    stlf = decomposition_model(
      STL(temp_air_meanC ~ season(period = "365 days")),
      NAIVE(season_adjust)
    ),
    #auto ARIMA
    arima = ARIMA(temp_air_meanC ~ pdq() + PDQ(period = "365 days"))
  )

fit_compare |> select(arima) |> filter(meta_station_id == "az01") |> report()
fit_compare |> select(arima) |> filter(meta_station_id == "az02") |> report()
# ARIMA(1,1,2)(0,1,0)[365] is best fit for ARIMA for Tucson
# for Yuma Valley, ARIMA(2,0,0)(0,1,0)[365] 
```

Compare accuracy

```{r}
fc <- fit_compare |> forecast(temp_test)
fc |> 
  # filter(.model == "arima") |> 
  autoplot(temp |> filter(year(datetime)>=2021), level = NULL)
accuracy(fc, temp_test, measures = point_accuracy_measures) |> arrange(meta_station_id, RMSE)
accuracy(fc, temp_test, measures = distribution_accuracy_measures) |> arrange(meta_station_id, CRPS)
accuracy(fc, temp_test, measures = interval_accuracy_measures) |> arrange(meta_station_id, winkler)
```
Again, seasonal naive and ARIMA are about equivalent.

```{r}
fit_compare |> select(snaive) |> filter(meta_station_id == "az01") |> gg_tsresiduals()
```

Umm.... why are all the residuals before a certain date 0?

# Comparing accuracy

So, like, actual comparison of accuracy should involve forecasting 1 day ahead at a bunch of randomly chosen dates, right?

